[profile.default]
src = "contracts"
test = "contracts/test"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
gas_reports = ["Boon"]
fs_permissions = [{ access = "read", path = "./test-vectors" }]

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 32
fail_on_revert = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = 8453 }
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532 }
